Add scripts for issue 3648 (internal review)
LuxoftSDL/sdl_atf_test_scripts pull request #107
Opened 2021-04-01 10:05 UTC by VjKlepikov

ATF Test Scripts to check 3648

This PR is **[ready]** for review.

### Summary
New ATF scripts to check the issue.

### ATF version
develop

### Changelog

##### Enhancements
    New scripts
   
### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-04-05 08:55 UTC, GetmanetsIrina approved these changes

2021-04-06 01:43 UTC, dboltovskyi requested changes

2021-04-06 01:43 UTC, dboltovskyi commented on test_scripts/Policies/HMI_PTU/022_No_Connection_days_trigger.lua
> +---------------------------------------------------------------------------------------------------
I would rename both scripts to `...No_App_connected_...`

2021-04-06 01:43 UTC, dboltovskyi commented on test_scripts/Policies/HMI_PTU/022_No_Connection_days_trigger.lua
> +  common.setSDLIniParameter, {"HMICapabilitiesCacheFile", ""})
Why do we need to set this parameter? Looks like this setting is not required.

2021-04-06 08:24 UTC, VjKlepikov commented
@dboltovskyi Thank you for the review. All comments have been processed

2021-04-06 17:24 UTC, dboltovskyi approved these changes

2021-04-07 08:14 UTC, merged