Add scripts for issue 3668 (internal review)
LuxoftSDL/sdl_atf_test_scripts pull request #108
Opened 2021-04-02 11:10 UTC by VjKlepikov

ATF Test Scripts to check 3668

This PR is **[ready]** for review.

### Summary
New ATF scripts to check the issue.

### ATF version
develop

### Changelog

-     New scripts
-     New test set for the issues in scope of 7.1 release

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-04-07 02:25 UTC, dboltovskyi requested changes

2021-04-07 02:25 UTC, dboltovskyi commented on test_scripts/Defects/7_1/3668_App_resets_UserLocation.lua
> +  hmi:ExpectRequest("UI.SetGlobalProperties", dataToHMI)
Isn't it supposed to be `RC` interface?

2021-04-07 02:25 UTC, dboltovskyi commented on test_scripts/Defects/7_1/3668_App_resets_UserLocation.lua
> +    :Do(function(_, data)
Fix indentation

2021-04-07 07:13 UTC, VjKlepikov commented
@dboltovskyi Thank you for the review. All comments have been processed.

2021-04-07 15:21 UTC, dboltovskyi approved these changes

2021-04-09 09:49 UTC, GetmanetsIrina approved these changes

2021-04-09 10:46 UTC, merged