Coverage extending
LuxoftSDL/sdl_atf_test_scripts pull request #109
Opened 2021-04-05 07:44 UTC by GetmanetsIrina

ATF Test Scripts to check #[FORDTCN-11191](https://adc.luxoft.com/jira/browse/FORDTCN-11191)

This PR is **ready** for review.

### Summary
Extended coverage for the issue according to [comment](https://adc.luxoft.com/jira/browse/FORDTCN-11191?focusedCommentId=2393103&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2393103) 

### ATF version
develop

### Changelog
* Added new scripts
* Updated test set for 7.1 release with new scripts
* Single script for the issue was moved to a folder

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-04-06 10:04 UTC, VjKlepikov approved these changes

2021-04-07 23:31 UTC, dboltovskyi requested changes

2021-04-07 23:31 UTC, dboltovskyi commented on test_scripts/Defects/7_1/3620/common.lua
> +      }
I would move expected result to the scripts `2` and `5` (as it's currently done for scripts `1`, `3`, `4`)

2021-04-07 23:31 UTC, dboltovskyi commented on test_sets/Defects/Defects_release_7_1.txt
> +./test_scripts/Defects/7_1/3620/3620_5_RPC_Service_NACK_protected_non_existed_session_id.lua
I would renumber scripts in a following way:
```
3620_1_RPC_Service_NACK_invalid_bson.lua
3620_2_RPC_Service_NACK_protected_invalid_bson.lua
3620_3_RPC_Service_NACK_non_existed_session_id.lua
3620_4_RPC_Service_NACK_protected_non_existed_session_id.lua
3620_5_RPC_Service_NACK_before_OnSystemTimeReady.lua
```

2021-04-08 07:43 UTC, GetmanetsIrina commented
All comments have been processed. @dboltovskyi  Please review

2021-04-11 00:59 UTC, dboltovskyi approved these changes

2021-04-12 07:42 UTC, merged