Add test script for issue 1896 (Internal review)
LuxoftSDL/sdl_atf_test_scripts pull request #110
Opened 2021-04-05 11:55 UTC by VjKlepikov

ATF Test Scripts to check # 

This PR is **[ready]** for review.

### Summary
New ATF script to check the issue.

### ATF version
develop

### Changelog

- Added new scripts
- Updated test set for 7.1 release with new scripts

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-04-05 12:43 UTC, GetmanetsIrina requested changes

2021-04-05 12:43 UTC, GetmanetsIrina commented on test_scripts/Defects/7_1/1896_SDL_does_not_send_HeartBeat_request_to_Mobile_HeartBeatTimeout_is_Zero.lua
> +  ignoreSDLHeartBeatACK = true
I think that there is no need to set `ignoreSDLHeartBeatACK` to `true` value

2021-04-05 12:43 UTC, GetmanetsIrina commented on test_scripts/Defects/7_1/1896_SDL_does_not_send_HeartBeat_request_to_Mobile_HeartBeatTimeout_is_Zero.lua
> +  local session = common.mobile.createSession(1, 1, pMobSessionConfig)
Please define app id in local variable

2021-04-05 12:43 UTC, GetmanetsIrina commented on test_scripts/Defects/7_1/1896_SDL_does_not_send_HeartBeat_request_to_Mobile_HeartBeatTimeout_is_Zero.lua
> +      :Do(function(_, d1)
This block Do can be removed, because the HMI app id is not used in this particular script

2021-04-05 12:43 UTC, GetmanetsIrina commented on test_scripts/Defects/7_1/1896_SDL_does_not_send_HeartBeat_request_to_Mobile_HeartBeatTimeout_is_Zero.lua
> +          session:ExpectNotification("OnPermissionsChange")
Expctation for `OnPermissionsChange` also can be removed

2021-04-05 12:43 UTC, GetmanetsIrina commented on test_scripts/Defects/7_1/1896_SDL_does_not_send_HeartBeat_request_to_Mobile_HeartBeatTimeout_is_Zero.lua
> +runner.Step("SDL respond ACK to HeartBeat request and does not send HeartBeat request to mobile app",
```suggestion
runner.Step("SDL responds with ACK to HB request and does not request HB to mobile app",
```

2021-04-05 12:43 UTC, GetmanetsIrina commented on test_scripts/Defects/7_1/1896_SDL_does_not_send_HeartBeat_request_to_Mobile_HeartBeatTimeout_is_Zero.lua
> +runner.Step("Activate App", common.activateApp)
I believe that app activation can be omitted(remove activation step from the description in case activation will be removed)

2021-04-05 13:46 UTC, VjKlepikov commented
@GetmanetsIrina Thank you for the review, all commits have been processed

2021-04-06 09:47 UTC, GetmanetsIrina approved these changes

2021-04-12 20:36 UTC, dboltovskyi requested changes

2021-04-12 20:36 UTC, dboltovskyi commented on test_scripts/Defects/7_1/1896_SDL_does_not_send_HeartBeat_request_to_Mobile_HeartBeatTimeout_is_Zero.lua
> +  -- Expect HB from SDL on mobile app
Suppose we need to correct this as `Not expect ...`

2021-04-12 20:36 UTC, dboltovskyi commented on test_scripts/Defects/7_1/1896_SDL_does_not_send_HeartBeat_request_to_Mobile_HeartBeatTimeout_is_Zero.lua
> +  sendHBFromMobile)
Please make this in one line

2021-04-12 20:36 UTC, dboltovskyi commented on test_scripts/Defects/7_1/1896_SDL_does_not_send_HeartBeat_request_to_Mobile_HeartBeatTimeout_is_Zero.lua
> +  { "HeartBeatTimeout", 0 })
Please make this in one line

2021-04-12 20:36 UTC, dboltovskyi commented on test_scripts/Defects/7_1/1896_SDL_does_not_send_HeartBeat_request_to_Mobile_HeartBeatTimeout_is_Zero.lua
> +  answerHeartbeatFromSDL = true,
I suppose we need to set `answerHeartbeatFromSDL` to `false` since HB is not expected from SDL

2021-04-13 09:53 UTC, VjKlepikov commented
@dboltovskyi  Thank you for the review, all commits have been processed

2021-04-13 13:01 UTC, dboltovskyi approved these changes

2021-04-14 11:57 UTC, merged