[Issue-1002] Add script for issue 1002 [internal review]
LuxoftSDL/sdl_atf_test_scripts pull request #121
Opened 2021-05-20 14:33 UTC by VjKlepikov

ATF Test Scripts to check [FORDTCN-11982](https://adc.luxoft.com/jira/browse/FORDTCN-11982)

This PR is **[ready]** for review.

### Summary
New ATF scripts to check the issue.

### ATF version
develop

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-05-20 19:27 UTC, dboltovskyi requested changes

2021-05-20 19:27 UTC, dboltovskyi commented on test_scripts/Defects/5_1/1002_SDL_sends_StopAudioStream_in_case_User_Exit_during_Audio_Video_streaming.lua
> +  { appID = common.app.getHMIId(), reason = "USER_EXIT" })
For better stability I would move this action to the end of function (before any expectation)

2021-05-20 19:27 UTC, dboltovskyi commented on test_scripts/Defects/5_1/1002_SDL_sends_StopAudioStream_in_case_User_Exit_during_Audio_Video_streaming.lua
> +-- send Navigation.StopStream request to HMI
Please add list dashes. E.g.:
```
SDL does:
 - expectation 1
 - expectation 2
```

2021-05-20 19:27 UTC, dboltovskyi commented on test_scripts/Defects/5_1/1002_SDL_sends_StopAudioStream_in_case_User_Exit_during_Audio_Video_streaming.lua
> +  end)
I would correct indentations across all script

2021-05-20 19:27 UTC, dboltovskyi commented on test_scripts/Defects/5_1/1002_SDL_sends_StopAudioStream_in_case_User_Exit_during_Audio_Video_streaming.lua
> +  :Times(AtLeast(1))
Not sure whether we have to use `AtLeast` here

2021-05-21 08:51 UTC, VjKlepikov commented
@dboltovskyi Thank you for the review, all comments have been processed

2021-05-21 14:17 UTC, dboltovskyi approved these changes
@VjKlepikov Thank you for updates

2021-05-28 07:49 UTC, merged