Feature/sdl 0192 button subscription response from hmi [internal review]
LuxoftSDL/sdl_atf_test_scripts pull request #126
Opened 2021-07-07 13:04 UTC by VjKlepikov

ATF Test Scripts to check [FORDTCN-12168](https://adc.luxoft.com/jira/browse/FORDTCN-12168)

This PR is **[ready]** for review.

### Summary
Scripts for "Button subscription response from hmi"

### ATF version
[8.0.0_version_bump](https://github.com/smartdevicelink/sdl_atf/tree/feature/8.0.0_version_bump)

### Changelog

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-07-08 07:29 UTC, VNikiforov-dev commented on test_scripts/API/ButtonSubscription/002_Subscribe_CUSTOM_BUTTON_Success.lua
> +common.runner.Step("Start SDL, HMI, connect Mobile, start Session", common.start)
add button to HMI capabilities during start HMI:
common.runner.Step("Start SDL, HMI, connect Mobile, start Session", common.start, { common.addButtonToCapabilities(common.custom_button_obj) })

2021-07-08 07:54 UTC, VNikiforov-dev commented on test_scripts/API/ButtonSubscription/002_Subscribe_CUSTOM_BUTTON_Success.lua
> +common.runner.Step("Start SDL, HMI, connect Mobile, start Session", common.start)
addButtonToCapabilities implemented in common_buttonSubscription.lua in PR https://github.com/LuxoftSDL/sdl_atf_test_scripts/pull/127

2021-07-08 12:48 UTC, VNikiforov-dev commented on test_scripts/API/ButtonSubscription/002_Subscribe_CUSTOM_BUTTON_Success.lua
> +common.runner.Step("Subscribe on Soft button", common.registerSoftButton)
Extra step in the test case?

2021-07-08 14:09 UTC, VNikiforov-dev commented on test_scripts/API/ButtonSubscription/005_Subscribe_button_SDL_send_UnsubscribeButton_after_Subscribe_SUCCESS_timeout.lua
> +local himCID
himCID is used only in a function rpcGenericError. Maybe moving the variable declaration to function? (to narrow the scope)

2021-07-08 15:00 UTC, VNikiforov-dev commented on test_scripts/API/ButtonSubscription/common_buttonSubscription.lua
> +  m.getHMIConnection(pAppId):ExpectRequest("Buttons.SubscribeButton", { m.getHMIAppId(), buttonName = "CUSTOM_BUTTON" })
```suggestion
  m.getHMIConnection(pAppId):ExpectRequest("Buttons.SubscribeButton", { appID = m.getHMIAppId(pAppId), buttonName = "CUSTOM_BUTTON" })
```

2021-07-12 20:49 UTC, dboltovskyi requested changes
@VjKlepikov Please notice:

This is 1st part of the review which is related to existing files/scripts.
2nd part will be related to a new scripts.

Besides the files in this PR please make the following updates:

1. Remove expectation on `Buttons.OnButtonSubscription` in all files in `user_modules` folder and sub-folders (or replace by appropriate new request where applicable)

2. Prepare a separate PR with removal of `Buttons.OnButtonSubscription` in `sdl_atf` repo in `modules/connecttest.lua`

2021-07-12 20:49 UTC, dboltovskyi commented on test_scripts/SDL5_0/MobileVersioning/PlayPauseButton/002_play_pause_v4_invalid_data.lua
> +    end)
In line `56` there is an expectation on `Buttons.OnButtonSubscription`. Suppose it needs to be replaced by `Buttons.UnsubscribeButton` request

2021-07-13 08:28 UTC, VjKlepikov commented on test_scripts/Smoke/API/042_SubscribeButton_Non_Media_PositiveCase_SUCCESS.lua
> +  "PRESET_8",
according to requirements https://adc.luxoft.com/jira/browse/APPLINK-14516?src=confmacro

2021-07-13 08:50 UTC, VjKlepikov commented on test_scripts/iAP2TransportSwitch/001_happy_path.lua
> +--runner.Step("Connect USB Device", connectUSBDevice)
my mistake during debug

2021-07-13 12:56 UTC, VjKlepikov commented
@dboltovskyi All the above comments have been processed
PR for ATF is created https://github.com/LuxoftSDL/sdl_atf/pull/7

2021-07-14 03:07 UTC, dboltovskyi requested changes
Please notice this is 2nd iteration of review.

2021-07-14 03:07 UTC, dboltovskyi commented on test_scripts/API/ButtonSubscription/038_Subscribe_CUSTOM_BUTTON_HMI_does_not_respond.lua
> + :Do(function()
Please fix indentation

2021-07-14 03:07 UTC, dboltovskyi commented on test_scripts/API/ButtonSubscription/040_Subscribe_CUSTOM_BUTTON_twise_IGNORED.lua
> +------------------------------------------------------------------------------------------------------------------------
Typo in script name: `twise`

2021-07-14 12:40 UTC, VjKlepikov commented on test_scripts/API/ButtonSubscription/009_SubscribeButton_INVALID_request_INVALID_DATA.lua
> +  common.getMobileSession():Send(msg)
The basic idea to check for incorrect structure ({... , {}}) I'm not sure if we can check this with SendRPC ()

2021-07-14 23:24 UTC, dboltovskyi requested changes

2021-07-14 23:24 UTC, dboltovskyi commented on test_scripts/API/ButtonSubscription/011_SubscribeButton_twise_the_same_button_IGNORED.lua
> +------------------------------------------------------------------------------------------------------------------------
Typo in script name: `twise`.

2021-07-14 23:24 UTC, dboltovskyi commented on test_scripts/API/ButtonSubscription/012_UnsunscribeButton_twise_the_same_button_IGNORED.lua
> +------------------------------------------------------------------------------------------------------------------------
Typo in script name: `twise`.

2021-07-14 23:24 UTC, dboltovskyi commented on test_scripts/API/ButtonSubscription/027_SubscribeButton_Resumption_Unexpected_disconect.lua
> +------------------------------------------------------------------------------------------------------------------------
Typo in script name: `disconect`.

2021-07-14 23:24 UTC, dboltovskyi commented on test_scripts/API/ButtonSubscription/029_SubscribeButton_Unexpected_disconect_HMI_responds_ERROR_CODE.lua
> +------------------------------------------------------------------------------------------------------------------------
Typo in script name: `disconect`.

2021-07-14 23:24 UTC, dboltovskyi commented on test_scripts/API/ButtonSubscription/030_SubscribeButton_on_different_buttons_Unexpected_disconect.lua
> +------------------------------------------------------------------------------------------------------------------------
Typo in script name: `disconect`.

2021-07-14 23:24 UTC, dboltovskyi commented on test_scripts/API/ButtonSubscription/031_SubscribeButton_Unexpected_disconect_HMI_doesn_t_response_timeout.lua
> +------------------------------------------------------------------------------------------------------------------------
Typo in script name: `disconect`.

2021-07-14 23:24 UTC, dboltovskyi commented on test_scripts/API/ButtonSubscription/041_Subscribe_CUSTOM_BUTTON_Resumption_Unexpected_disconect.lua
> +------------------------------------------------------------------------------------------------------------------------
Typo in script name: `disconect`.

2021-07-14 23:24 UTC, dboltovskyi commented on test_scripts/API/ButtonSubscription/042_Unsubscribe_CUSTOM_BUTTON_Resumption_Unexpected_disconect.lua
> +------------------------------------------------------------------------------------------------------------------------
Typo in script name: `disconect`.

2021-07-14 23:24 UTC, dboltovskyi commented on test_scripts/API/ButtonSubscription/001_Subscribe_Unsubscribe_Button_Success.lua
> +		{ appSessionId1, buttonName, common.isNotExpected })
Please replace all tabs by spaces => as it's already done in other scripts

2021-07-15 21:09 UTC, dboltovskyi requested changes
Please also check scripts correspond to test set in Jira

2021-07-21 14:24 UTC, closed without merging