Extend coverage for SDL-0264 Preparation to testing of Separating the change of Audible status [internal review]
LuxoftSDL/sdl_atf_test_scripts pull request #132
Opened 2021-09-07 10:33 UTC by VjKlepikov

ATF Test Scripts to check [FORDTCN-12446](https://adc.luxoft.com/jira/browse/FORDTCN-12446)

This PR is **[not ready]** for review.

### Summary
Extend coverage for [SDL-0264] Preparation to testing of Separating the change of Audible status

### ATF version
[develop]

2021-09-09 23:50 UTC, dboltovskyi requested changes

2021-09-09 23:50 UTC, dboltovskyi commented on test_scripts/API/SeparatingChangeAudibleStatus/002_activate_App_audioStreamingState_during_PHONE_CALL_events.lua
> +common.Step("Print failed TCs", common.printFailedTCs)
Within fix suggested for `common.checkHMIStatus()` script fails in some cases for `Action_Phone_call_end_app_none` step.

2021-09-09 23:50 UTC, dboltovskyi commented on test_scripts/API/SeparatingChangeAudibleStatus/003_PHONE_CALL_events_during_audio_video.lua
> +    [3] = { e = common.userActions.deactivateApp,    l = "LIMITED" }, -- a = "AUDIBLE",      v = "STREAMABLE"
I would propose to uncoment this code otherwise within fix suggested for common.checkHMIStatus() script would fail

2021-09-09 23:50 UTC, dboltovskyi commented on test_scripts/API/SeparatingChangeAudibleStatus/common.lua
> +m.cloneTable = utils.cloneTable
Remove unused functions (e.g. `testSettings`)

2021-09-09 23:50 UTC, dboltovskyi commented on test_scripts/API/SeparatingChangeAudibleStatus/common.lua
> +local test = require("user_modules/dummy_connecttest")
Try to not use `test` module. E.g. `test.mobileSession` can be easily replaced by the function from `action` module

2021-09-10 08:35 UTC, VNikiforov-dev requested changes

2021-09-13 16:05 UTC, dboltovskyi commented on test_scripts/API/SeparatingChangeAudibleStatus/001_different_types_audioStreamingState_by_PHONE_CALL_event.lua
> +  [002] = { t = "MEDIA",      m = false,  s = {
Agreed to retain these combinations

2021-09-13 20:09 UTC, dboltovskyi requested changes

2021-09-14 12:04 UTC, VNikiforov-dev approved these changes

2021-09-14 16:03 UTC, dboltovskyi commented on test_sets/separating_audible_status_change.txt
> +./test_scripts/API/SeparatingAudibleStatusChange/003_PHONE_CALL_events_during_audio_video.lua
Issue is fixed in `8.0` branch so agreed to left scripts as is

2021-09-14 16:05 UTC, dboltovskyi approved these changes

2021-09-14 16:05 UTC, dboltovskyi commented
PR can be moved to Open

2021-09-16 09:44 UTC, closed without merging