SDL must respond UNSUPPORTED_RESOURCE to mobile app in case SDL 4.0 feature is required to be ommited in implementation
LuxoftSDL/sdl_atf_test_scripts pull request #134
Opened 2021-09-28 09:35 UTC by VNikiforov-dev

ATF Test Scripts to check #[2399]

This PR is **ready for Internal** review.

### Summary
Scripts to check 2399 issue

### ATF version
develop

### Changelog
- Added scripts to check 2399 issue

### CLA
- [ ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-09-28 12:30 UTC, aderiabin approved these changes

2021-09-28 12:30 UTC, aderiabin commented on test_scripts/Defects/8_0/2399__SDL_respond_UNSUPPORTED_RESOURCE_in_case_SDL_4_0_was_omited.lua
> +---------------------------------------------------------------------------------------------------
@VNikiforov-dev Please add this script to `test_sets/Defects/Defects_release_8_0.txt` test set

2021-09-28 12:30 UTC, aderiabin commented on test_scripts/Defects/8_0/2399__SDL_respond_UNSUPPORTED_RESOURCE_in_case_SDL_4_0_was_omited.lua
> +-- 1) App is registered and activated
@VNikiforov-dev I would propose to use numeration with dots for test steps
``` 1) -> 1. ```

2021-09-28 12:30 UTC, aderiabin commented on test_scripts/Defects/8_0/2399__SDL_respond_UNSUPPORTED_RESOURCE_in_case_SDL_4_0_was_omited.lua
> +-- 2) Mobile app requests SystemRequest(QUERY_APPS)
@VNikiforov-dev Please use one of `App` or `Mobile app` in bound of whole script

2021-09-28 12:30 UTC, aderiabin commented on test_scripts/Defects/8_0/2399__SDL_respond_UNSUPPORTED_RESOURCE_in_case_SDL_4_0_was_omited.lua
> +local protocol_version = 3
@VNikiforov-dev I would propose to use `camelCase` naming style instead `snake_case` here
```
local protocol_version = 3
=>
local protocolVersion = 3
```
And rename this variable according its purpose 
```
protocolVersion => maxSdlProtocolVersion
```

2021-09-29 02:16 UTC, dboltovskyi requested changes

2021-09-29 02:16 UTC, dboltovskyi commented on test_scripts/Defects/8_0/2399__SDL_respond_UNSUPPORTED_RESOURCE_in_case_SDL_4_0_was_omited.lua
> +runner.Step("Stop SDL", common.postconditions)
Please add script to test set for issues of 8.0: https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_sets/Defects/Defects_release_8_0.txt

2021-09-29 02:16 UTC, dboltovskyi commented on test_scripts/Defects/8_0/2399__SDL_respond_UNSUPPORTED_RESOURCE_in_case_SDL_4_0_was_omited.lua
> +-- User story: https://github.com/smartdevicelink/sdl_core/issues/2399
Replace `User story` by `Issue`

2021-09-29 15:13 UTC, dboltovskyi approved these changes

2021-09-30 06:14 UTC, VjKlepikov approved these changes

2021-09-30 15:14 UTC, closed without merging