Add script(s) for issue 3674
LuxoftSDL/sdl_atf_test_scripts pull request #136
Opened 2021-09-30 14:14 UTC by VNikiforov-dev

ATF Test Scripts to check #[3674]

This PR is **not ready for Internal** review.

### Summary
Scripts to check 3674 issue

### ATF version
develop

### Changelog
- Added scripts to check 3674 issue

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2021-09-30 19:37 UTC, dboltovskyi requested changes

2021-09-30 19:37 UTC, dboltovskyi commented on test_scripts/Defects/8_0/3674_SDL_sends_OnAppRegistered_before_app_has_valid_internal_HMI_state.lua
> +end
Please correct indentations in this function

2021-09-30 19:37 UTC, dboltovskyi commented on test_scripts/Defects/8_0/3674_SDL_sends_OnAppRegistered_before_app_has_valid_internal_HMI_state.lua
> +    local appParams = utils.cloneTable(common.app.getParams())
Using of `cloneTalbe()` is not required

2021-09-30 19:37 UTC, dboltovskyi commented on test_scripts/Defects/8_0/3674_SDL_sends_OnAppRegistered_before_app_has_valid_internal_HMI_state.lua
> +    return false
Please provide the reason of false

2021-09-30 19:37 UTC, dboltovskyi commented on test_scripts/Defects/8_0/3674_SDL_sends_OnAppRegistered_before_app_has_valid_internal_HMI_state.lua
> +-- 2. HMI receive BC.OnAppRegistered
`receive` => `receives`

2021-10-01 10:16 UTC, VjKlepikov requested changes

2021-10-01 10:16 UTC, VjKlepikov commented on test_scripts/Defects/8_0/3674_SDL_sends_OnAppRegistered_before_app_has_valid_internal_HMI_state.lua
> +    common.getMobileSession():ExpectNotification("OnSystemRequest"):Times(2)
Please align
```suggestion
     common.getMobileSession():ExpectNotification("OnSystemRequest"):Times(2)
```

2021-10-05 16:27 UTC, dboltovskyi approved these changes

2021-10-05 16:28 UTC, closed without merging

2021-10-05 16:35 UTC, dboltovskyi commented
Moved to `https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2593`