[Internal review] Add scripts for issue 3804
LuxoftSDL/sdl_atf_test_scripts pull request #143
Opened 2021-11-05 08:33 UTC by VjKlepikov

ATF Test Scripts to check [FORDTCN-12562](https://luxproject.luxoft.com/jira/browse/FORDTCN-12562)

This PR is **[ready]** for review.

### Summary
New ATF scripts to check the 3804 issue.

### ATF version
develop

### Changelog
New script

2021-11-08 01:36 UTC, dboltovskyi approved these changes

2021-11-08 14:39 UTC, VNikiforov-dev requested changes

2021-11-08 14:39 UTC, VNikiforov-dev commented on test_scripts/Defects/8_1/3804_1_RAI_use_hmiCapabilities_from_cache_file.lua
> +  common.getHMIConnection():SendNotification("BasicCommunication.OnExitAllApplications", { reason = "SUSPEND" })
Using two styles of call (sendNotification / ExpectNotification and etc) in a file:
1. in line 39 and other - common.**getHMIConnection**():SendNotification 
2. in line 72 - common.**hmi.getConnection()**:ExpectNotification 

Could you lead to one of style? (Better use style №2)

2021-11-11 09:46 UTC, VjKlepikov commented
@VNikiforov-dev Please find the update in [a1f72a0f](https://github.com/LuxoftSDL/sdl_atf_test_scripts/pull/143/commits/a1f72a0f080bc8c932c46db03bd3448c5d04c080), [938237](https://github.com/LuxoftSDL/sdl_atf_test_scripts/pull/143/commits/9382374bafe76f7822a05e049fb04f22527ecbd9)

2021-11-11 13:14 UTC, VNikiforov-dev approved these changes

2021-11-12 13:48 UTC, closed without merging

2021-12-22 17:15 UTC, dboltovskyi commented
Moved to `https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2610`