add test scripts for defect 944
LuxoftSDL/sdl_atf_test_scripts pull request #146
Opened 2021-11-10 13:54 UTC by VjKlepikov

ATF Test Scripts to check [FORDTCN-12562](https://luxproject.luxoft.com/jira/browse/FORDTCN-12562)

This PR is **[ready]** for review.

### Summary
New ATF scripts to check the 3804 issue.

### ATF version
develop

### Changelog
New script

2021-11-10 17:56 UTC, dboltovskyi requested changes

2021-11-10 17:56 UTC, dboltovskyi commented on test_scripts/Defects/8_1/994_SDL_sends_appName_in_vrSynonyms_and_ttsName_in_case_of_separated_structure_in_json_file.lua
> +            for _, appData in ipairs(data1.params.applications) do
This piece of code doesn't validate all required applications
It validates only the ones which are provided in `applications` array. 
On a current develop this list contains only default `"Test Application"` and misses apps provided in `json`
I would add an additional check on number of apps provided in `applications` array before checking parameters in `checkParams()` function

2021-11-10 21:25 UTC, VNikiforov-dev requested changes

2021-11-11 08:50 UTC, VjKlepikov commented
@dboltovskyi @VNikiforov-dev Please find updates in [f144cba](https://github.com/LuxoftSDL/sdl_atf_test_scripts/pull/146/commits/f144cbaaba46657929727e5398e69024592e7660)

2021-11-11 13:11 UTC, VNikiforov-dev approved these changes

2021-11-16 16:53 UTC, dboltovskyi approved these changes
@VjKlepikov Thank you for updates

2021-11-16 17:00 UTC, closed without merging