[Internal review] Add scripts for issues/2664
LuxoftSDL/sdl_atf_test_scripts pull request #155
Opened 2021-12-22 21:11 UTC by VNikiforov-dev

ATF Test Scripts to check [FORDTCN-11994](https://luxproject.luxoft.com/jira/browse/FORDTCN-11994)

This PR is **[ready]** for review.

### Summary
New ATF scripts to check the 2664 issue

### ATF version
develop

### Changelog
Update old PR with script for issue 980
Update test sets

2021-12-22 22:10 UTC, dboltovskyi requested changes

2021-12-22 22:10 UTC, dboltovskyi commented on test_scripts/RC/CLIMATE_RADIO/SetInteriorVehicleData/028_SUCCESS_cut_off_params_for_another_module.lua
> +	local cid = commonRC.getMobileSession():SendRPC("SetInteriorVehicleData", { moduleData = moduleData })
Please fix indentations

2021-12-22 22:10 UTC, dboltovskyi commented on test_scripts/RC/CLIMATE_RADIO/SetInteriorVehicleData/028_SUCCESS_cut_off_params_for_another_module.lua
> +        return false, "SDL resends to HMI the not related to module type parameters"
Propose to rephrase to:
> SDL transfers to HMI parameters not related to module

2021-12-22 22:10 UTC, dboltovskyi commented on test_scripts/RC/CLIMATE_RADIO/SetInteriorVehicleData/028_SUCCESS_cut_off_params_for_another_module.lua
> +-- 1) Transfer request to HMI without data related to RADIO module
Don't use numbers in `SDL does` section. Suggest to use `-` or letters

2021-12-22 22:10 UTC, dboltovskyi commented on test_sets/SDL5_0/rc_CLIMATE_RADIO.txt
> +./test_scripts/RC/CLIMATE_RADIO/SetInteriorVehicleData/028_SUCCESS_cut_off_params_for_another_module.lua
Please add script to `Defects_releases_4_x_and_5_x.txt` test set since issue `2664` had been fixed in scope of `5.0.0` release

2021-12-23 10:41 UTC, VNikiforov-dev commented
@dboltovskyi Done in da0338c

2021-12-23 13:48 UTC, dboltovskyi requested changes

2021-12-23 13:48 UTC, dboltovskyi commented on test_sets/Defects/Defects_releases_4_x_and_5_x.txt
> +./test_scripts/RC/CLIMATE_RADIO/SetInteriorVehicleData/028_SUCCESS_cut_off_params_for_another_module.lua
Please rename script appropriate to the issue it is related to

2021-12-23 13:56 UTC, VjKlepikov approved these changes

2021-12-23 13:56 UTC, VjKlepikov commented on test_scripts/RC/CLIMATE_RADIO/SetInteriorVehicleData/028_SUCCESS_cut_off_params_for_another_module.lua
> +-- 1) SDL, HMI, Mobile session started
```suggestion
-- 1) SDL, HMI, Mobile session are started
```

2021-12-23 13:56 UTC, VjKlepikov commented on test_scripts/RC/CLIMATE_RADIO/SetInteriorVehicleData/028_SUCCESS_cut_off_params_for_another_module.lua
> +--  - Transfer request to HMI without data related to RADIO module
```suggestion
--  - transfer request to HMI without data related to RADIO module
```

2021-12-24 15:42 UTC, VNikiforov-dev commented
Thanks for your review. Done in 88fcaf4

2021-12-24 15:44 UTC, VNikiforov-dev commented
@dboltovskyi @VjKlepikov Thanks for your review. Done in 88fcaf4

2021-12-24 16:52 UTC, dboltovskyi approved these changes
@VNikiforov-dev Thank you for updates

2021-12-28 09:57 UTC, closed without merging