Add script for 3888 issue
LuxoftSDL/sdl_atf_test_scripts pull request #173
Opened 2022-04-18 12:12 UTC by GetmanetsIrina

ATF Test Scripts to check #[FORDTCN-12994](https://luxproject.luxoft.com/jira/browse/FORDTCN-12994)

This PR is **ready for internal review** for review.

### Summary
Added new script to check resumption of CreateInteractionChoiceSet with and without VR command

### ATF version
develop

### Changelog
1. New script is added
2. Created script is added to the test set 8_2

### CLA
- [ ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2022-04-19 09:28 UTC, VjKlepikov approved these changes

2022-04-26 08:34 UTC, VjKlepikov requested changes
Please add test for resumption

2022-04-27 12:18 UTC, GetmanetsIrina commented
Please find update in [d729878](https://github.com/LuxoftSDL/sdl_atf_test_scripts/pull/173/commits/d729878e01b4f7f31c135b1d52dd3278fc921406)

2022-04-28 07:58 UTC, VjKlepikov requested changes

2022-04-28 07:58 UTC, VjKlepikov commented on test_scripts/Defects/8_2/3888_2_CreateInteractionChoiceSet_resumption_ignition_off.lua
> +  runner.Step("Unexpected disconnect", ignitionOff)
```suggestion
  runner.Step("Ignition off", ignitionOff)
```

2022-04-28 08:26 UTC, VjKlepikov requested changes
I propose to add resumption case for DeleteInteractionChoiceSet request and move common functions to common module

2022-04-28 08:26 UTC, VjKlepikov commented on test_scripts/Defects/8_2/3888_2_CreateInteractionChoiceSet_resumption_ignition_off.lua
> +-- 4. Ignition on is performed
```suggestion
-- 2. Ignition off is performed
-- 3. Ignition on is performed
```

2022-04-29 08:59 UTC, GetmanetsIrina commented
@VjKlepikov, please review

2022-05-03 07:46 UTC, VjKlepikov requested changes

2022-05-03 07:46 UTC, VjKlepikov commented on test_scripts/Defects/8_2/3888/common.lua
> +m.getHMIAppId = actions.getHMIAppId
Should we use the mentioned proxy functions that are not in the scripts?

2022-05-03 07:46 UTC, VjKlepikov commented on test_scripts/Defects/8_2/3888/common.lua
> +    m.getHMIConnection():SendNotification("BasicCommunication.OnExitAllApplications", { reason = "IGNITION_OFF" })
```suggestion
    m.getHMIConnection():SendNotification("BasicCommunication.OnExitAllApplications", { reason = "IGNITION_OFF" })
```
```suggestion
     m.getHMIConnection():SendNotification("BasicCommunication.OnExitAllApplications", { reason = "IGNITION_OFF" })
```

2022-05-03 07:46 UTC, VjKlepikov commented on test_scripts/Defects/8_2/3888/3888_4_CreateInteractionChoiceSet_resumption_two_sets_ignition_off.lua
> +common.Step("CreateInteractionChoiceSet witout vr command", common.createInteractionChoiceSet,
```suggestion
common.Step("CreateInteractionChoiceSet witout vr command", common.createInteractionChoiceSet,
```
```suggestion
common.Step("CreateInteractionChoiceSet without vr command", common.createInteractionChoiceSet,
```

2022-05-03 07:46 UTC, VjKlepikov commented on test_scripts/Defects/8_2/3888/3888_4_CreateInteractionChoiceSet_resumption_two_sets_ignition_off.lua
> +common.Step("CreateInteractionChoiceSet witout vr command", common.createInteractionChoiceSet,
```suggestion
common.Step("CreateInteractionChoiceSet witout vr command", common.createInteractionChoiceSet,
```
```suggestion
common.Step("CreateInteractionChoiceSet without vr command", common.createInteractionChoiceSet,
```

2022-05-03 07:46 UTC, VjKlepikov commented on test_scripts/Defects/8_2/3888/3888_6_DeleteInteractionChoiceSet_during_resumption_unexpected_disc.lua
> +--  - send RAI response with "SUCCESS" result code after resumption data is succeeded
```suggestion
--  - send RAI response with "SUCCESS" result code after resumption data is succeeded
```
```suggestion
--  - send RAI response with "RESUME_FAILED" result code after resumption data is succeeded
```

2022-05-03 07:46 UTC, VjKlepikov commented on test_scripts/Defects/8_2/3888/3888_6_DeleteInteractionChoiceSet_during_resumption_unexpected_disc.lua
> +--  - send RAI response with "SUCCESS" result code after resumption data is succeeded
```suggestion
--  - send RAI response with "SUCCESS" result code after resumption data is succeeded
```
```suggestion
--  - send RAI response with "RESUME_FAILED" result code
```

2022-05-03 07:46 UTC, VjKlepikov commented on test_scripts/Defects/8_2/3888/3888_6_DeleteInteractionChoiceSet_during_resumption_unexpected_disc.lua
> +--  - send RAI response with "SUCCESS" result code after resumption data is succeeded
```suggestion
--  - send RAI response with "SUCCESS" result code after resumption data is succeeded
```
```suggestion
--  - send RAI response with "RESUME_FAILED" result code
```

2022-05-03 07:46 UTC, VjKlepikov commented on test_scripts/Defects/8_2/3888/3888_7_DeleteInteractionChoiceSet_during_resumption_ignition_off.lua
> +---------------------------------------------------------------------------------------------------
Please update the description according to the steps

2022-05-03 07:46 UTC, VjKlepikov commented on test_scripts/Defects/8_2/3888/3888_7_DeleteInteractionChoiceSet_during_resumption_ignition_off.lua
> +---------------------------------------------------------------------------------------------------
Please update the description according to the steps

2022-05-04 11:17 UTC, GetmanetsIrina commented
@VjKlepikov, please find update in [8f758fb](https://github.com/LuxoftSDL/sdl_atf_test_scripts/pull/173/commits/8f758fb0f9fbaa9591b9175b40d86269a3058113)

2022-05-05 09:29 UTC, VjKlepikov approved these changes

2022-06-08 06:48 UTC, GetmanetsIrina commented
moved to open

2022-06-08 06:48 UTC, closed without merging