Script for defect 2401
LuxoftSDL/sdl_atf_test_scripts pull request #176
Opened 2022-04-19 14:27 UTC by GetmanetsIrina

ATF Test Scripts to check #[FORDTCN-12011](https://luxproject.luxoft.com/jira/browse/FORDTCN-12011)

This PR is **ready for internal review** for review.

### Summary
Added script to cover PerformInteraction RPC with ChoiceSets with and without VR command

### ATF version
develop

### Changelog
- Added new script
- Test set updated with new added script

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2022-04-19 15:25 UTC, VjKlepikov requested changes

2022-04-19 15:25 UTC, VjKlepikov commented on test_scripts/Defects/5_0/2401_CreateInteractionChoiceSet_with_ChoiceSet_with_and_without_vr_command.lua
> +      createICSParams.without_vr.choiceSet.choiceID
```suggestion
      createICSParams.with_vr.choiceSet[1].choiceID,
      createICSParams.without_vr.choiceSet[1].choiceID
```

2022-04-20 09:51 UTC, GetmanetsIrina commented on test_scripts/Defects/5_0/2401_CreateInteractionChoiceSet_with_ChoiceSet_with_and_without_vr_command.lua
> +      createICSParams.without_vr.choiceSet.choiceID
Please find update in [5fae54d](https://github.com/LuxoftSDL/sdl_atf_test_scripts/pull/176/commits/5fae54d151cade644620b13efe83b5b62d040038)

2022-04-20 11:24 UTC, VjKlepikov approved these changes

2022-04-22 12:20 UTC, GetmanetsIrina commented
moved to open

2022-04-22 12:33 UTC, closed without merging