Add test scripts for issue 2467 [internal review]
LuxoftSDL/sdl_atf_test_scripts pull request #177
Opened 2022-04-20 10:17 UTC by VjKlepikov

ATF Test Scripts to check #[issue number in sdl_core repository]

This PR is **[ready]** for internal review.

### Summary
Add test scripts for issue 2467

### ATF version
latest

### Changelog
 Added new script
 Test set updated with new added script

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2022-04-21 14:12 UTC, GetmanetsIrina requested changes

2022-04-21 14:12 UTC, GetmanetsIrina commented on test_scripts/Defects/5_0/2467_Policy_table_corupted_after_first_ign_cycle.lua
> +      for i = 1, common.mobile.getAppsCount() do
function can be called only for one used session

2022-04-22 06:20 UTC, VjKlepikov commented
@GetmanetsIrina Please find an update [e15373b](https://github.com/LuxoftSDL/sdl_atf_test_scripts/pull/177/commits/e15373be554dd14911775e7676318798632f1744)

2022-04-22 11:37 UTC, GetmanetsIrina approved these changes

2022-04-26 11:55 UTC, VjKlepikov commented
move to open

2022-04-26 11:55 UTC, closed without merging