Additional case for 1921 issue
LuxoftSDL/sdl_atf_test_scripts pull request #178
Opened 2022-04-22 14:09 UTC by GetmanetsIrina

ATF Test Scripts to check #[FORDTCN-11966](https://luxproject.luxoft.com/jira/browse/FORDTCN-11966)

This PR is **ready for internal review**

### Summary
Added case with empty array after unknown parameter

### ATF version
develop

### Changelog
- updated script for 1921 issue 

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2022-04-28 10:21 UTC, VjKlepikov requested changes

2022-04-28 10:21 UTC, VjKlepikov commented on test_scripts/Defects/4_5/1921_Invalid_PT_after_cutting_unknow_values.lua
> +        hmi_levels = { "BACKGROUND", "FULL", "LIMITED" },
```suggestion
        hmi_levels = { "BACKGROUND", "FULL", "LIMITED" , "NONE"},
```

2022-04-28 10:21 UTC, VjKlepikov commented on test_scripts/Defects/4_5/1921_Invalid_PT_after_cutting_unknow_values.lua
> +      }
SubscribeVehicleData = {
        hmi_levels = { "BACKGROUND", "FULL", "LIMITED", "NONE" },
        parameters = { unknownParameter }
      }

2022-04-28 10:21 UTC, VjKlepikov commented on test_scripts/Defects/4_5/1921_Invalid_PT_after_cutting_unknow_values.lua
> +      }
Seems HMILevel for application is "NONE"

2022-04-29 09:28 UTC, GetmanetsIrina commented
@VjKlepikov, please review

2022-05-02 14:34 UTC, VjKlepikov approved these changes

2022-05-04 11:32 UTC, GetmanetsIrina commented
moved to open

2022-05-04 11:32 UTC, closed without merging