Add test scripts for issue 12937 [internal review]
LuxoftSDL/sdl_atf_test_scripts pull request #189
Opened 2022-06-06 07:29 UTC by VjKlepikov

ATF Test Scripts to check [FORDTCN-12937](https://luxproject.luxoft.com/jira/browse/FORDTCN-12937)

This PR is **[ready ]** for internal review.

### Summary
Add test scripts for issue 3895 

### ATF version
latest

### Changelog
New scripts are added
Test set is updated with new scripts

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2022-06-07 14:13 UTC, GetmanetsIrina requested changes

2022-06-07 14:13 UTC, GetmanetsIrina commented on test_scripts/Defects/8_2/3895_SDL_sends_redundant_BC.PolicyUpdate.lua
> +runner.Step("Clean environment without SDL log", common.preconditions)
```suggestion
runner.Step("Clean environment", common.preconditions)
```

2022-06-07 14:13 UTC, GetmanetsIrina commented on test_scripts/Defects/8_2/3895_SDL_sends_redundant_BC.PolicyUpdate.lua
> +-- 1. HMI sends SDL.OnPolicyUpdate notification during 'ApplicationListUpdateTimeout' is expired
```suggestion
-- 1. HMI sends SDL.OnPolicyUpdate notification during 'ApplicationListUpdateTimeout' when timeout is almost expired
```

2022-06-07 14:13 UTC, GetmanetsIrina commented on test_scripts/Defects/8_2/3895_SDL_sends_redundant_BC.PolicyUpdate.lua
> +    end)
I propose to add extra wait for this function to avoid the situation when extra message comes after step is finished.

2022-06-07 14:13 UTC, GetmanetsIrina commented on test_sets/Defects/Defects_release_8_2.txt
> +./test_scripts/Defects/8_2/3895_SDL_sends_redundant_BC.PolicyUpdate.lua
Please remove the dot from the script name
```suggestion
./test_scripts/Defects/8_2/3895_SDL_sends_redundant_BC_PolicyUpdate.lua
```

2022-06-07 14:38 UTC, VjKlepikov commented
@GetmanetsIrina Please find the update in [d8fea918](https://github.com/LuxoftSDL/sdl_atf_test_scripts/pull/189/commits/d8fea918940d674ab2a0389bfedaac4d80c97d80)

2022-06-08 09:37 UTC, GetmanetsIrina requested changes

2022-06-08 09:37 UTC, GetmanetsIrina commented on test_scripts/Defects/8_2/3895_SDL_sends_redundant_BC_PolicyUpdate.lua
> +-- 1. HMI sends SDL.OnPolicyUpdate notification during 'ApplicationListUpdateTimeout' when timeout is almost expired
Please apply the same update to the description

2022-06-08 09:37 UTC, GetmanetsIrina commented on test_scripts/Defects/8_2/3895_SDL_sends_redundant_BC_PolicyUpdate.lua
> +  utils.wait(3000)
Maybe 1 sec is enough?

2022-06-08 10:45 UTC, GetmanetsIrina approved these changes

2022-06-10 08:06 UTC, VjKlepikov commented
move to open

2022-06-10 08:06 UTC, closed without merging