add test scripts for issue 3857
LuxoftSDL/sdl_atf_test_scripts pull request #196
Opened 2022-06-28 12:17 UTC by VjKlepikov

ATF Test Scripts to check #[FORDTCN-12637](https://luxproject.luxoft.com/jira/browse/FORDTCN-12637)

This PR is **[ready]** for review.

### Summary
Add test scripts for issue 3857

### ATF version
latest

### Changelog
The new script is added
The test set is updated with new scripts

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2022-06-29 13:31 UTC, GetmanetsIrina requested changes

2022-06-29 13:31 UTC, GetmanetsIrina commented on test_scripts/Defects/8_2/3857_Crash_on_Ignition_Off_during_registering_Apps.lua
> +-- In case:
```suggestion
-- Steps:
```

2022-06-29 13:31 UTC, GetmanetsIrina commented on test_scripts/Defects/8_2/3857_Crash_on_Ignition_Off_during_registering_Apps.lua
> +-- 1. Register 5 Apps during Ignition OFF
```suggestion
-- 1. Mobile app starts registration of 5 apps
-- 2. Ignition off is performed during apps registration
```

2022-06-29 13:31 UTC, GetmanetsIrina commented on test_scripts/Defects/8_2/3857_Crash_on_Ignition_Off_during_registering_Apps.lua
> +-- Description: The crash occurs on Ignition OFF during registering Apps
Please define description from SDL perspective lile `There is no SDL crash on ignition off ....`

2022-06-29 13:31 UTC, GetmanetsIrina commented on test_scripts/Defects/8_2/3857_Crash_on_Ignition_Off_during_registering_Apps.lua
> +  local isFailed = false
Propose to rename to isDisconnected

2022-06-29 13:46 UTC, VjKlepikov commented
@GetmanetsIrina Please find the update in [8cd6c](https://github.com/LuxoftSDL/sdl_atf_test_scripts/pull/196/commits/8cd6c811ca1e81119a009fedeca50b6612a7a31b)

2022-06-29 14:45 UTC, GetmanetsIrina approved these changes

2022-06-30 07:13 UTC, VjKlepikov commented
move to open

2022-06-30 07:13 UTC, closed without merging