[CCB-3175] Add test scripts to check defect 3175
LuxoftSDL/sdl_atf_test_scripts pull request #77
Opened 2020-09-03 11:37 UTC by aderiabin

ATF Test Scripts to check issue [3174](https://github.com/smartdevicelink/sdl_core/issues)

This PR is **ready** for review.

### Summary
Add test script for defect 3174

### Changelog
 - Added test script for defect 3174

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-09-03 17:08 UTC, dboltovskyi requested changes

2020-09-03 17:08 UTC, dboltovskyi commented on test_scripts/Defects/7_0/3175/3175_8_VR.OnLanguageChange_during_PTU_after_receiving_of_SystemRequest.lua
> +-- 1. HMI sends VR.OnLanguageChange after receiving of SystemRequest response on App during PTU processing
...  SystemRequest response by App ...

2020-09-03 17:08 UTC, dboltovskyi commented on test_scripts/Defects/7_0/3175/common_3175.lua
> +  actions.run.wait(3000)
I would add this delay into each `performPTU...` function for better robustness

2020-09-03 19:43 UTC, dboltovskyi approved these changes

2020-09-04 11:23 UTC, GetmanetsIrina approved these changes

2020-09-07 07:17 UTC, closed without merging