[SDL-0308] Extending coverage for feature
LuxoftSDL/sdl_atf_test_scripts pull request #82
Opened 2020-10-06 11:42 UTC by GetmanetsIrina

ATF Test Scripts to check #[FORDTCN-7953](https://adc.luxoft.com/jira/browse/FORDTCN-7953)

This PR is **ready** for review.

### Summary
Extending coverage for feature 0308 `Add a Reason Parameter to All Protocol NAKs`

### ATF version
develop

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

2020-10-07 08:46 UTC, VjKlepikov approved these changes

2020-10-07 08:46 UTC, VjKlepikov commented on test_scripts/Protocol/NACKReason/007_Force_protected_Video_Audio_Services_NACK.lua
> +-- - respond with NAck to StartService request because because unprotected service is requested
```suggestion
-- - respond with NAck to StartService request because unprotected service is requested
```

2020-10-07 08:46 UTC, VjKlepikov commented on test_scripts/Protocol/NACKReason/005_Wrong_app_type_Video_Audio_Services_NACK.lua
> +-- Description: SDL provides reason information in NAck message
```suggestion
-- Description: SDL provides reason information in NACK message
```
I would propose to change NAck to NACK to improve readability according to common practice

2020-10-07 08:46 UTC, VjKlepikov commented on test_sets/protocol_nak_reason_param.txt
> +./test_scripts/Protocol/NACKReason/014_Invalid_time_RPC_Service_NACK.lua
I would propose to add scripts In case mobile app starts (not protected) AUDIO/VIDEO service  two times

2020-10-07 08:46 UTC, VjKlepikov commented on test_scripts/Protocol/NACKReason/005_Wrong_app_type_Video_Audio_Services_NACK.lua
> +
```suggestion
--
```
I would propose to comment out this line

2020-10-07 12:14 UTC, GetmanetsIrina commented
@VjKlepikov, all comments are addressed. Please review.

2020-10-12 08:33 UTC, aderiabin approved these changes

2020-10-13 17:03 UTC, dboltovskyi requested changes

2020-10-14 07:14 UTC, GetmanetsIrina commented on test_scripts/Protocol/NACKReason/005_Wrong_app_type_Video_Audio_Services_NACK.lua
> +  { 1, common.serviceType.PCM, audioServiceParams.reqParams, audioServiceParams.nackParams })
I believe that it's enough one script for checking of reason absence in NACK messages. I think that checking of reason absence in NACK messages in each script this is overhead.

2020-10-14 08:06 UTC, GetmanetsIrina commented
@dboltovskyi, all comments are addressed. Please review.

2020-10-14 14:49 UTC, dboltovskyi approved these changes

2020-10-16 07:49 UTC, merged